### ISSUE TITLE
User data Websocket

### ISSUE THREAD

**Issue by talvasconcelos** [aarongarvey/binance#10]
Hi, can't seem to get user data websocket to work.
 I tried the example on github but i get:
```.then((ws) => {
    ^

TypeError: Cannot read property 'then' of undefined
```

if i comment out 'then' it does nothing...

**Comment by aarongarvey** [comment]
I used the user data websocket to update the README just a couple days ago and had no issues.  It would be nice to have some more code/context around just the error that you provided.  It looks like the promise may not be being returned for some reason, that or you haven't defined/instantiated it properly.

**Comment by talvasconcelos** [comment]
Sorry, here's the test:
```
const api = require('binance');
const config = require('./config')
const binanceRest = new api.BinanceRest({
    key: '*****************************', // Get this from your account on binance.com
    secret: '************************', // Same for this
    timeout: 15000, // Optional, defaults to 15000, is the request time out in milliseconds
    recvWindow: 60000, // Optional, defaults to 5000, increase if you're getting timestamp errors
    disableBeautification: false
    /*
     * Optional, default is false. Binance's API returns objects with lots of one letter keys.  By
     * default those keys will be replaced with more descriptive, longer ones.
     */
});

const binanceWS = new api.BinanceWS();

binanceWS.onUserData(binanceRest, (data) => {
        console.log(data)
    }, 60000) // Optional, how often the keep alive should be sent in milliseconds
    .then((ws) => {
        // websocket instance available here
    });
```

**Comment by aarongarvey** [comment]
So it would seem that I accidentally removed the return statement for the outer promise :) and that's why it's undefined.  I'll have the change in and an update published to npm shortly.  In the mean time, if you want to get it working, just add a `return` at the beginning of line 41 in `lib\ws.js`.  I've not used the websocket portion of the API personally, only the REST, so I'm sure there's more work that could be done with it.  If you encounter any other issues, or think of any functionality you'd like to have please let me know.
