### ISSUE TITLE
Error: Response code 400 - code: -1022, msg: 'Signature for this request is not valid.'

### ISSUE THREAD

**Issue by askmike** [aarongarvey/binance#34]
Hey,

The binance module (1.3.1) is not working for me:

    const binance = require('binance');

    const client = new binance.BinanceRest({
      key: 'x',
      secret: 'y',
      timeout: 15000,
      recvWindow: 60000, // suggested by binance
      disableBeautification: false,
      handleDrift: true
    });

    client.account({}, console.log);

Returns the following:

    Error: Response code 400
        at Request.request [as _callback] (/Users/pear/projects/gekko/node_modules/binance/lib/rest.js:90:34)
        at Request.self.callback (/Users/pear/projects/gekko/node_modules/request/request.js:186:22)
        at emitTwo (events.js:125:13)
        at Request.emit (events.js:213:7)
        at Request.<anonymous> (/Users/pear/projects/gekko/node_modules/request/request.js:1163:10)
        at emitOne (events.js:115:13)
        at Request.emit (events.js:210:7)
        at IncomingMessage.<anonymous> (/Users/pear/projects/gekko/node_modules/request/request.js:1085:12)
        at Object.onceWrapper (events.js:312:19)
        at emitNone (events.js:110:20) { code: -1022, msg: 'Signature for this request is not valid.' }

Setting [this line](https://github.com/aarongarvey/binance/blob/master/lib/rest.js#L80) to `1022` instead of `1021` did not fix it for me. Do you have any ideas?

**Comment by askmike** [comment]
(see https://github.com/askmike/gekko/issues/1788)

**Comment by aarongarvey** [comment]
That's really odd that you're getting an invalid signature response.  I ran your exact code, adding in an artificial 10 second drift and things go as expected.  The initial request fails, we get the code -1021 that the time is off, server time is retrieved, and then a -9915 ms drift is calculated, request is sent again and the positive result is logged to console.  Same goes for a request without the artificial drift.

If you can reproduce the error, throw in a log statement on line 64 of lib/rest.js that will print out the contents of the `options` object.  Something like `console.log(JSON.stringify(options))`.  Also, can you double check that the API Key and secret are correct and still valid?  The only way I'm able to get a -1022 is by altering my secret.  If you wanna force the drift handling code because your clock is synced you can change the `_getTime()` function to `return new Date().getTime() + 10000;`

**Comment by askmike** [comment]
@aarongarvey apologies, this is the second time I reported a bug which was not actually there (first one you had already fixed). It seems I was using an old key/secret pair which no longer works.

**Comment by rxcod9** [comment]
Try this

https://github.com/zoeyg/binance/pull/75

**Comment by noahwalugembe** [comment]
i am getting Signature for this request is not valid. error my code just work only for a small time and the stopes. the cod blow has bean working for 4 weeks but now it gives me
{ Signature for this request is not valid. error}

PATH = '/api/v3/account'

    timestamp = int(time.time() * 1000)
    params = {
       
       'recvWindow': 5000,
       'timestamp': timestamp
    }

    query_string = urlencode(params)
    params['signature'] = hmac.new(self.SECRET_KEY.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256).hexdigest()

    url = urljoin(self.BASE_URL, PATH)
    r = requests.get(url, headers=self.headers, params=params)
